### ISSUE TITLE
How do I give access to the S3 bucket?

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#13]
<img width="1131" alt="screenshot 2018-01-18 23 00 43" src="https://user-images.githubusercontent.com/1232282/35138457-8595a268-fca3-11e7-9202-19414f00baa5.png">

**Comment by joemellin** [comment]
Fixed it!

**Comment by ext0** [comment]
For anyone having this issue in the feature, check your CORS access rules for the S3 bucket!
