### ISSUE TITLE
Create a My Acres page

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#15]
It should show a list of the acres that I purchased and link to them.

![log in copy 3](https://user-images.githubusercontent.com/1232282/35139576-98b669c2-fca8-11e7-9703-a223a7a64115.png)

**Comment by joemellin** [comment]
There needs to be a "You conserved an acre" alert (green) on the my acres page after you conserve something.

**Comment by joemellin** [comment]
A toast works for this.

**Comment by demidn** [comment]
[bugfix]
