### ISSUE TITLE
Add Previous and Next buttons to the acres

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#28]
On each acre in a forest,

There should be a "Next" and "Previous" button that navigate through the forest ID's 

If you are at the beginning of the acres, there is no previous button.
If you are at the end of the acres in a forest, there is no next button.

Also, can these buttons be hovers over on top of the 360 image?

**Comment by ext0** [comment]
Added acre navigation buttons in 71d5dc99b666b48a22594a52b89a7bd5fd829f2f
