### ISSUE TITLE
Add ability to add partners to a forest.

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#31]
A forest can have many partners.

Each partner has:
- Title (USA funder)
- Name (Global Conservation Fund)
- URL (http://www.globalconservationfund.com)

**Comment by ext0** [comment]
Progress made in 21919fb60894464737eb5d7de7324b099cd36b37. Will follow up with another commit implemented partner functionality to the UI for adding forests.

**Comment by ext0** [comment]
Finished implementaton in 93d4528
