### ISSUE TITLE
Convert coordinates to latitude and longitude on forest view page.

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#32]
15.7835° N, 90.2308° W

Latitude = (Top + Bottom) / 2 rounded to nearest 4th decimal place.  Ex: 15.7835° N

If Latitude > 0 add ° and "N" to the end of it.
If latitude < 0 add ° and "S" to the end of it and normalize it (make it positive).

Longitude = (Right + Left) / 2 rounded to nearest 4th decimal place.  Ex: 90.2308° W

If Longitude > 0 add ° and "E" to the end of it.
If Longitude < 0 add ° and "W" to the end of it and normalize it (make it positive).

**Comment by ext0** [comment]
Added latitude longitude parsing and display to the acre overview page.
