### ISSUE TITLE
Update UI of Forest View Page

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#34]
After adding the listed functionality.  

- [x] #33 
- [x] #32 
- [x] #31 
- [ ] #30 

Update the page to look like this:

![view acre page](https://user-images.githubusercontent.com/1232282/36394018-e06f0eb2-1577-11e8-85d5-bf8de807982d.png)

**Comment by ext0** [comment]
I've got this commit ready to be pushed - but waiting on my AWS account to be ready (issue with Amazon support) so I can test the S3 bucket quality changes before pushing. Should be out by the end of the day.

**Comment by ext0** [comment]
Implemented in ec6fb11, however the location functionality needs to be implemented in #42. At the moment, just using Guatemala as a placeholder.
