### ISSUE TITLE
Somethings funky

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#35]
I added forest to this map:

https://conserve-dev.herokuapp.com/forests/21

But there isn't anything on the map.  Thoughts?

**Comment by demidn** [comment]
@joemellin @ext0 for some reasons there is parcel 261 without area data. not sure how it was added - at front end there is not null validation.
Anyway would be good to update db and add NOT NULL check to column
I have updated frontend for now to filter parcels without area, so it will be drawn on the map.

**Comment by joemellin** [comment]
Thanks! Updated
