### ISSUE TITLE
Update Admin Panel

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#36]
<img width="1066" alt="screenshot 2018-02-22 21 17 14" src="https://user-images.githubusercontent.com/1232282/36576358-ce70c156-1815-11e8-94f6-311add58cd31.png">

Make the columns

Parcel ID: 
Forest Name:
Top:
Bottom:
Right:
Left:
Picture: Y (True) N (False)
Panorama: Y (True) N (False)

**Comment by ext0** [comment]
For clarification - do you want the top, bottom, left, and right to be in their degree format with 4 decimal points? And are we removing the cost and purchased columns?

**Comment by joemellin** [comment]
RE: top, bottom, left, and right - let's do the inputted number (no rounding) and no degree 

This is for the admin interface so I just want to be able to see what is there and then in the future sort by it.

**Comment by ext0** [comment]
Resolved in ec6fb11
