### ISSUE TITLE
Fix Parcel ID increment issue

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#37]
When you create a parcel ID it goes up in increments of 10.  Not by 1.

So, if you create a parcel, it should be #1 and the next one #2 and the next #3

**Comment by demidn** [comment]
@joemellin It is ClearDB strategy of primary key auto increament.
http://w2.cleardb.net/faqs/#general_16
So we can not change it. Anyway, primary key is something technical part, used inside application, not public.

**Comment by joemellin** [comment]
@demidn I get that, it is just that we want to have an acre ID so that we can match each acre with each latitude and longitude and each photo and each panorama. 

Otherwise to find an acre we need to search by both the top, bottom, right and left to find a specific acre.  

Can you add another field that is visible in admin, that is the Acre #?  

So on create, it counts the number of acres in a forest (N) and it assigns the new acre the ID of N+1?

**Comment by ext0** [comment]
In my instance using MySQL, the auto-increment is the standard +1, maybe redeploy with MySQL instead? The docker instance automatically comes with MySQL and should have the proper functionality.

**Comment by joemellin** [comment]
Also, we could just have a write-in field that is only visible to admin that is called acre number and when admin creates the user they can fill in the number and it is only used for administrative purposes.

**Comment by joemellin** [comment]
Let's just leave it the way it is for now.

**Comment by demidn** [comment]
@joemellin I had it almost ready, when you closed it. So committed today. Now you have text field in edit parcel dialog - you can either enter number there, or leave it blank. If you leave it blank - it will be auto created as max(number) + 1 among parcels belonged to this forest.
