### ISSUE TITLE
Back to forests link on wrong page

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#38]
I wasn't clear enough with my spec for #33 

It should link  (be where the Acre word is)
<img width="987" alt="screenshot 2018-02-23 08 26 22" src="https://user-images.githubusercontent.com/1232282/36598917-4d1382c0-1873-11e8-88cd-5614a58503f8.png">

to this page:
<img width="906" alt="screenshot 2018-02-23 08 26 37" src="https://user-images.githubusercontent.com/1232282/36598923-5203d01e-1873-11e8-93ac-38b950852499.png">

**Comment by ext0** [comment]
I've got the new back button implemented in bff5a4c, should I remove the old one that was incorrectly implemented?
