### ISSUE TITLE
Something is generally not working on the forest detail pages

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#39]
I think it is part of the #28 

Previous and Next does not change the panoramic image.  

And the info of if the acre was purchased is gone.

Ex: This land has been purchased and it doesn't show that here
https://conserve-dev.herokuapp.com/parcels/51

**Comment by ext0** [comment]
Hi Joe, I've got the panorama fix in 2787c53, what should the acre page show if it's already been purchased?

**Comment by joemellin** [comment]
@ext0 this was already working

See #17
