### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#4]
**Backend** 

**Forests**
- Description - > Text
- Images of animals - > Jpg. 
- Have PARCELS
- Has a cost per parcel -> Decimal / Float

**Parcels**
- Belongs to forest
- Photos / 360 photos of parcel
- Boundary
    - Top -> Decimal / Float
    - Bottom -> Decimal / Float
    - Left -> Decimal / Float
    - Right -> Decimal / Float
- Center Point
    - Lat + Long

**User authentication**
- Facebook signup

**User**
- User has Profile name
- User has profile image
- User has transactions
- User has purchased Parcels

**Transactions**
- Stripe
- User purchases Parcel
- User can select purchase type / Self / Other / Anymous.

**Pages**:
https://invis.io/BGDSSZF39#/256703740_How_It_Works
- Index page
    - See grid of parcels on google maps
    - See if parcel is purchased or not
- Parcel detail page
    - If purchased
        - See who purchased it / or anon
    - Be able to purchase
- My Conservation
    - See list of conserved land by the user
- User profile
    - See user information and edit profile name
- Log in / Log out / sign up

**Admin needs to be able to add / edit parcles
Add / edit forests**

**Comment by joemellin** [comment]
@haleymellin hello

**Comment by joemellin** [comment]
Hey Demid can you update X

**Comment by joemellin** [comment]
@demidn The cost is on the forest not on the parcel.

Also, the parcels location needs to be updated.
 
We want to make rectangle  ex:
top: 37.7745° N
bottom: 37.7749° N
Right: 122.4194° W
Left: 122.4196° W

And then we need it to be in a format that can be used for this API:
https://developers.google.com/maps/documentation/javascript/examples/rectangle-simple

@demidn Do you know what format that should be? 
or @woodylama @programmerdiego ?

**Comment by woodylama** [comment]
Not sure I'm getting it right. But if I understood correctly all those points should be pulled from a JSON file?
