### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#41]
Why is the image quality reduced?

view after image is uploaded
<img width="988" alt="screenshot 2018-02-24 23 47 32" src="https://user-images.githubusercontent.com/1232282/36638527-2ede62f2-19bd-11e8-93a5-39c34897a341.png">

actual image
<img width="1037" alt="screenshot 2018-02-24 23 47 24" src="https://user-images.githubusercontent.com/1232282/36638528-310e1946-19bd-11e8-858c-420b08921e8b.png">

**Comment by ext0** [comment]
Resolved in ec6fb11, had to do with image resizing and JPEG compression.
