### ISSUE TITLE
Move Cost to the Parcel

### ISSUE THREAD

**Issue by joemellin** [joemellin/conservethisacre#9]
The cost of a land should be on the "parcels" not on the "lands".

**Comment by demidn** [comment]
Could you please point me where we have it

**Comment by joemellin** [comment]
<img width="633" alt="screenshot 2018-01-22 21 26 49" src="https://user-images.githubusercontent.com/1232282/35259471-fae4a392-ffba-11e7-9721-38be6533648e.png">

**Comment by joemellin** [comment]
See the above is on the parcel not on the "land" or "forest"

**Comment by joemellin** [comment]
https://www.dropbox.com/s/bxmwblz5nthes83/Screenshot%202018-02-02%2007.42.31.png?dl=0

**Comment by joemellin** [comment]
cost should not be on the one with Latitude and Longitude

**Comment by joemellin** [comment]
so if I have 1000 Parcels in the same forest, they should be the same cost and that should be set once in the forest
